channels:
  - conda-forge
dependencies:
  - h5py
  - matplotlib
  - numpy
  - pip
  - numpy
  - pandas
  - plotly==4.1.0
  - notebook>=5.3
  - ipywidgets>=7.2
  - voila
  - voila-gridstack
  - ipyleaflet
  - gunicorn==19.9.0
  - rise
  - pip:
      - dash-colorscales==0.0.4
      - voila-vuetify
      - jupyter_plotly_dash
      - jupyterlab_iframe